### PR TITLE
desktop view of recipe page

### PR DESCRIPTION
**Pull request by SpooossGaming**
i did the desktop view for the recipe page
also fixed the margin -20 thing

no picture or svg yet though

### CODE REVIEW

**Review by Douchebag — APPROVED** [review]
looks good

**Comment by ValurSV** [comment]
“Great work! 🎉 The implementation is clean, and I appreciate the attention to detail. Just a small suggestion: write your pull request in Icelandic, which could improve language skils. Overall, it’s shaping up nicely! Thanks for your effort! 🙌”

**Comment by SpooossGaming** [comment]
Small suggestion: no

**Comment by ValurSV** [comment]
Awesome job! 🚀✨ The code looks solid and your attention to detail is on point! 🔍👌 Just a tiny suggestion 📝: WRITE IN ICELANDIC, which could make your Icelandic even better! 💡💪 Overall, it’s coming together beautifully! 🌈🎉 Thanks for all the hard work! 🙏🔥🙌💯

**Comment by SpooossGaming** [comment]
im_finished

**Comment by ValurSV** [comment]
“WHOA!!! 🤩🚀💥🔥 This PR is ABSOLUTELY MINDBLOWING! 💻💣✨ You’re a coding wizard 🧙‍♂️🖥️✨—the way you’ve crafted this is pure magic! 🧙‍♀️⚡ Your attention to detail 🧐🔍💯 is beyond impressive! 😱🙌💎 Just the tiniest, teeniest suggestion 📝🤏: [insert suggestion here] could add a little extra sparkle ✨🌟 to [specific aspect]! But honestly, this is ALREADY LEGENDARY!!! 🎉💪🔥 You are SMASHING IT! 💥⚡👑💯 Keep slaying! 🔥🙌💥💣💥💻 YOU’RE A TOTAL ROCKSTAR! 🎸🤘💫🌟🌈👾🚀👑✨ Thank you SOOOO MUCH for your incredible effort! 🙏🙇‍♂️❤️‍🔥💥💻🔥🌈🔥🌟🙌💻🎉👾🚀🚀💯💯💯👑💥🌈🌟🎉💣💣🔥🔥🌟💎🌈💥⚡✨”

**Pull request merged**
